site_name: Reproducible Science and Programming Practices for Researchers
nav:
  - Getting Started: index.md
  - Software Setup:
      - Installation Guide Overview: setup/index.md
      #- Terminology: setup/terminology.md
      #- Command Line Tools: setup/commandLine.md
      - R: setup/r.md
      - Stata: setup/stata.md
      - Perl: setup/perl.md
      - Git: setup/gitInstall.md
      - Text Editor: setup/textEditor.md
      - Python: setup/python.md
      - Python Extras: setup/python-more.md
      - Build Tools/Make:
          - Why Build Tools?: setup/make-intro.md
          - Automation with Make: setup/make.md
          #    - Automation with Waf: setup/waf.md
          - Automation with Snakemake: setup/snakemake.md
      - Webscraping: setup/webscraping_drivers.md
      - Teamviewer: setup/teamviewer.md
  #  - Pandoc: setup/pandoc.md
  # - Matlab: setup/matlab.md
  # - Path Settings: setup/path-setting.md
  - Project Setup and Workflow Management:
      - Getting Started: workflow/index.md
      - Module/Directory Structure: workflow/directories.md
      #- Alternative module structure: workflow/directories_alt.md
      - Automation: workflow/automation.md
      - Documentation:
          - Documentation of Code and Workflow: workflow/doc.md
          - Documentation of New Data: workflow/doc_data.md
        #- Overview:
        #- Workflow in make: workflow/automation_workflow.md
      #- Versioning: workflow/versioning.md
      #- Data storage: workflow/data.md
      #- Documentation: workflow/doc.md
      #- Housekeeping: workflow/housekeeping.md
      #- Portability: workflow/portability.md
      - Checklist with Summary: workflow/checklist.md
  - Contact: contact.md
  - Acknowledgements: acknowledgement.md

theme:
  name: "material"

markdown_extensions:
  - admonition
